import Head from 'next/head'
import { ThemeProvider } from 'styled-components';
import defaultTheme from '~/theme';
import Header from '~/components/Header';
import Drawer from '~/components/Drawer';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider theme={defaultTheme}>
      <Head>
        <title>元大</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Drawer />
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default MyApp;
